// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/nodegraph/model/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Src            string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	SrcName        string                 `protobuf:"bytes,2,opt,name=srcName,proto3" json:"srcName,omitempty"`
	SrcNamespace   string                 `protobuf:"bytes,3,opt,name=srcNamespace,proto3" json:"srcNamespace,omitempty"`
	Dst            string                 `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	DstName        string                 `protobuf:"bytes,5,opt,name=dstName,proto3" json:"dstName,omitempty"`
	DstNamespace   string                 `protobuf:"bytes,6,opt,name=dstNamespace,proto3" json:"dstNamespace,omitempty"`
	ConnCount      int64                  `protobuf:"varint,7,opt,name=connCount,proto3" json:"connCount,omitempty"`
	ConnPersistent int64                  `protobuf:"varint,8,opt,name=connPersistent,proto3" json:"connPersistent,omitempty"`
	BytesSent      float64                `protobuf:"fixed64,9,opt,name=bytesSent,proto3" json:"bytesSent,omitempty"`
	BytesReceived  float64                `protobuf:"fixed64,10,opt,name=bytesReceived,proto3" json:"bytesReceived,omitempty"`
	Duration       float64                `protobuf:"fixed64,11,opt,name=duration,proto3" json:"duration,omitempty"`
	MaxDuration    float64                `protobuf:"fixed64,12,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionItem) Reset() {
	*x = ConnectionItem{}
	mi := &file_internal_proto_nodegraph_model_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionItem) ProtoMessage() {}

func (x *ConnectionItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_nodegraph_model_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionItem.ProtoReflect.Descriptor instead.
func (*ConnectionItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_nodegraph_model_model_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionItem) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *ConnectionItem) GetSrcName() string {
	if x != nil {
		return x.SrcName
	}
	return ""
}

func (x *ConnectionItem) GetSrcNamespace() string {
	if x != nil {
		return x.SrcNamespace
	}
	return ""
}

func (x *ConnectionItem) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *ConnectionItem) GetDstName() string {
	if x != nil {
		return x.DstName
	}
	return ""
}

func (x *ConnectionItem) GetDstNamespace() string {
	if x != nil {
		return x.DstNamespace
	}
	return ""
}

func (x *ConnectionItem) GetConnCount() int64 {
	if x != nil {
		return x.ConnCount
	}
	return 0
}

func (x *ConnectionItem) GetConnPersistent() int64 {
	if x != nil {
		return x.ConnPersistent
	}
	return 0
}

func (x *ConnectionItem) GetBytesSent() float64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ConnectionItem) GetBytesReceived() float64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *ConnectionItem) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ConnectionItem) GetMaxDuration() float64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *ConnectionItem) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_internal_proto_nodegraph_model_model_proto protoreflect.FileDescriptor

const file_internal_proto_nodegraph_model_model_proto_rawDesc = "" +
	"\n" +
	"*internal/proto/nodegraph/model/model.proto\x12\x15proto.nodegraph.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\x0eConnectionItem\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x18\n" +
	"\asrcName\x18\x02 \x01(\tR\asrcName\x12\"\n" +
	"\fsrcNamespace\x18\x03 \x01(\tR\fsrcNamespace\x12\x10\n" +
	"\x03dst\x18\x04 \x01(\tR\x03dst\x12\x18\n" +
	"\adstName\x18\x05 \x01(\tR\adstName\x12\"\n" +
	"\fdstNamespace\x18\x06 \x01(\tR\fdstNamespace\x12\x1c\n" +
	"\tconnCount\x18\a \x01(\x03R\tconnCount\x12&\n" +
	"\x0econnPersistent\x18\b \x01(\x03R\x0econnPersistent\x12\x1c\n" +
	"\tbytesSent\x18\t \x01(\x01R\tbytesSent\x12$\n" +
	"\rbytesReceived\x18\n" +
	" \x01(\x01R\rbytesReceived\x12\x1a\n" +
	"\bduration\x18\v \x01(\x01R\bduration\x12 \n" +
	"\vmaxDuration\x18\f \x01(\x01R\vmaxDuration\x126\n" +
	"\blastSeen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\blastSeenB?Z=github.com/k8spacket/k8spacket/internal/proto/nodegraph/modelb\x06proto3"

var (
	file_internal_proto_nodegraph_model_model_proto_rawDescOnce sync.Once
	file_internal_proto_nodegraph_model_model_proto_rawDescData []byte
)

func file_internal_proto_nodegraph_model_model_proto_rawDescGZIP() []byte {
	file_internal_proto_nodegraph_model_model_proto_rawDescOnce.Do(func() {
		file_internal_proto_nodegraph_model_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_nodegraph_model_model_proto_rawDesc), len(file_internal_proto_nodegraph_model_model_proto_rawDesc)))
	})
	return file_internal_proto_nodegraph_model_model_proto_rawDescData
}

var file_internal_proto_nodegraph_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_nodegraph_model_model_proto_goTypes = []any{
	(*ConnectionItem)(nil),        // 0: proto.nodegraph.model.ConnectionItem
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_proto_nodegraph_model_model_proto_depIdxs = []int32{
	1, // 0: proto.nodegraph.model.ConnectionItem.lastSeen:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_nodegraph_model_model_proto_init() }
func file_internal_proto_nodegraph_model_model_proto_init() {
	if File_internal_proto_nodegraph_model_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_nodegraph_model_model_proto_rawDesc), len(file_internal_proto_nodegraph_model_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_nodegraph_model_model_proto_goTypes,
		DependencyIndexes: file_internal_proto_nodegraph_model_model_proto_depIdxs,
		MessageInfos:      file_internal_proto_nodegraph_model_model_proto_msgTypes,
	}.Build()
	File_internal_proto_nodegraph_model_model_proto = out.File
	file_internal_proto_nodegraph_model_model_proto_goTypes = nil
	file_internal_proto_nodegraph_model_model_proto_depIdxs = nil
}
