{
 "title": "k8spacket - metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "namespace",
    "query": {
     "query": "label_values(k8s_packet_bytes_sent_sum, ns)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(k8s_packet_bytes_sent_sum{ns=~\"$ns\"}, src_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Increase bytes sent by workload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(k8s_packet_bytes_sent_sum{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)/sum(increase(k8s_packet_bytes_sent_count{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)",
     "legendFormat": "{{src_name}}"
    }
   ]
  },
  {
   "title": "Increase bytes received by workload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(k8s_packet_bytes_received_sum{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)/sum(increase(k8s_packet_bytes_received_count{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)",
     "legendFormat": "{{src_name}}"
    }
   ]
  },
  {
   "title": "Increase duration by workload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(k8s_packet_duration_seconds_sum{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)/sum(increase(k8s_packet_duration_seconds_count{ns=~\"$ns\", src_name=~\"$workload\"}[1m])) by (src_name)",
     "legendFormat": "{{src_name}}"
    }
   ]
  }
 ]
}