// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/tlsparser/model/model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=notBefore,proto3" json:"notBefore,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	ServerChain   string                 `protobuf:"bytes,3,opt,name=serverChain,proto3" json:"serverChain,omitempty"`
	LastScrape    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastScrape,proto3" json:"lastScrape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_internal_proto_tlsparser_model_model_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *Certificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *Certificate) GetServerChain() string {
	if x != nil {
		return x.ServerChain
	}
	return ""
}

func (x *Certificate) GetLastScrape() *timestamppb.Timestamp {
	if x != nil {
		return x.LastScrape
	}
	return nil
}

type TLSDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain             string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Dst                string                 `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Port               uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ClientTLSVersions  []string               `protobuf:"bytes,5,rep,name=clientTLSVersions,proto3" json:"clientTLSVersions,omitempty"`
	ClientCipherSuites []string               `protobuf:"bytes,6,rep,name=clientCipherSuites,proto3" json:"clientCipherSuites,omitempty"`
	UsedTLSVersion     string                 `protobuf:"bytes,7,opt,name=usedTLSVersion,proto3" json:"usedTLSVersion,omitempty"`
	UsedCipherSuite    string                 `protobuf:"bytes,8,opt,name=usedCipherSuite,proto3" json:"usedCipherSuite,omitempty"`
	Certificate        *Certificate           `protobuf:"bytes,9,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TLSDetails) Reset() {
	*x = TLSDetails{}
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSDetails) ProtoMessage() {}

func (x *TLSDetails) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSDetails.ProtoReflect.Descriptor instead.
func (*TLSDetails) Descriptor() ([]byte, []int) {
	return file_internal_proto_tlsparser_model_model_proto_rawDescGZIP(), []int{1}
}

func (x *TLSDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TLSDetails) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TLSDetails) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *TLSDetails) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TLSDetails) GetClientTLSVersions() []string {
	if x != nil {
		return x.ClientTLSVersions
	}
	return nil
}

func (x *TLSDetails) GetClientCipherSuites() []string {
	if x != nil {
		return x.ClientCipherSuites
	}
	return nil
}

func (x *TLSDetails) GetUsedTLSVersion() string {
	if x != nil {
		return x.UsedTLSVersion
	}
	return ""
}

func (x *TLSDetails) GetUsedCipherSuite() string {
	if x != nil {
		return x.UsedCipherSuite
	}
	return ""
}

func (x *TLSDetails) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type TLSConnection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Src             string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	SrcName         string                 `protobuf:"bytes,3,opt,name=srcName,proto3" json:"srcName,omitempty"`
	SrcNamespace    string                 `protobuf:"bytes,4,opt,name=srcNamespace,proto3" json:"srcNamespace,omitempty"`
	Dst             string                 `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	DstName         string                 `protobuf:"bytes,6,opt,name=dstName,proto3" json:"dstName,omitempty"`
	DstPort         uint32                 `protobuf:"varint,7,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	Domain          string                 `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	UsedTLSVersion  string                 `protobuf:"bytes,9,opt,name=usedTLSVersion,proto3" json:"usedTLSVersion,omitempty"`
	UsedCipherSuite string                 `protobuf:"bytes,10,opt,name=usedCipherSuite,proto3" json:"usedCipherSuite,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TLSConnection) Reset() {
	*x = TLSConnection{}
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConnection) ProtoMessage() {}

func (x *TLSConnection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tlsparser_model_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConnection.ProtoReflect.Descriptor instead.
func (*TLSConnection) Descriptor() ([]byte, []int) {
	return file_internal_proto_tlsparser_model_model_proto_rawDescGZIP(), []int{2}
}

func (x *TLSConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TLSConnection) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *TLSConnection) GetSrcName() string {
	if x != nil {
		return x.SrcName
	}
	return ""
}

func (x *TLSConnection) GetSrcNamespace() string {
	if x != nil {
		return x.SrcNamespace
	}
	return ""
}

func (x *TLSConnection) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *TLSConnection) GetDstName() string {
	if x != nil {
		return x.DstName
	}
	return ""
}

func (x *TLSConnection) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TLSConnection) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TLSConnection) GetUsedTLSVersion() string {
	if x != nil {
		return x.UsedTLSVersion
	}
	return ""
}

func (x *TLSConnection) GetUsedCipherSuite() string {
	if x != nil {
		return x.UsedCipherSuite
	}
	return ""
}

func (x *TLSConnection) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_internal_proto_tlsparser_model_model_proto protoreflect.FileDescriptor

const file_internal_proto_tlsparser_model_model_proto_rawDesc = "" +
	"\n" +
	"*internal/proto/tlsparser/model/model.proto\x12\x15proto.tlsparser.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n" +
	"\vCertificate\x128\n" +
	"\tnotBefore\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x126\n" +
	"\bnotAfter\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12 \n" +
	"\vserverChain\x18\x03 \x01(\tR\vserverChain\x12:\n" +
	"\n" +
	"lastScrape\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastScrape\"\xd0\x02\n" +
	"\n" +
	"TLSDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x10\n" +
	"\x03dst\x18\x03 \x01(\tR\x03dst\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12,\n" +
	"\x11clientTLSVersions\x18\x05 \x03(\tR\x11clientTLSVersions\x12.\n" +
	"\x12clientCipherSuites\x18\x06 \x03(\tR\x12clientCipherSuites\x12&\n" +
	"\x0eusedTLSVersion\x18\a \x01(\tR\x0eusedTLSVersion\x12(\n" +
	"\x0fusedCipherSuite\x18\b \x01(\tR\x0fusedCipherSuite\x12D\n" +
	"\vcertificate\x18\t \x01(\v2\".proto.tlsparser.model.CertificateR\vcertificate\"\xd7\x02\n" +
	"\rTLSConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x18\n" +
	"\asrcName\x18\x03 \x01(\tR\asrcName\x12\"\n" +
	"\fsrcNamespace\x18\x04 \x01(\tR\fsrcNamespace\x12\x10\n" +
	"\x03dst\x18\x05 \x01(\tR\x03dst\x12\x18\n" +
	"\adstName\x18\x06 \x01(\tR\adstName\x12\x18\n" +
	"\adstPort\x18\a \x01(\rR\adstPort\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12&\n" +
	"\x0eusedTLSVersion\x18\t \x01(\tR\x0eusedTLSVersion\x12(\n" +
	"\x0fusedCipherSuite\x18\n" +
	" \x01(\tR\x0fusedCipherSuite\x126\n" +
	"\blastSeen\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\blastSeenB?Z=github.com/k8spacket/k8spacket/internal/proto/tlsparser/modelb\x06proto3"

var (
	file_internal_proto_tlsparser_model_model_proto_rawDescOnce sync.Once
	file_internal_proto_tlsparser_model_model_proto_rawDescData []byte
)

func file_internal_proto_tlsparser_model_model_proto_rawDescGZIP() []byte {
	file_internal_proto_tlsparser_model_model_proto_rawDescOnce.Do(func() {
		file_internal_proto_tlsparser_model_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_tlsparser_model_model_proto_rawDesc), len(file_internal_proto_tlsparser_model_model_proto_rawDesc)))
	})
	return file_internal_proto_tlsparser_model_model_proto_rawDescData
}

var file_internal_proto_tlsparser_model_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_tlsparser_model_model_proto_goTypes = []any{
	(*Certificate)(nil),           // 0: proto.tlsparser.model.Certificate
	(*TLSDetails)(nil),            // 1: proto.tlsparser.model.TLSDetails
	(*TLSConnection)(nil),         // 2: proto.tlsparser.model.TLSConnection
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_proto_tlsparser_model_model_proto_depIdxs = []int32{
	3, // 0: proto.tlsparser.model.Certificate.notBefore:type_name -> google.protobuf.Timestamp
	3, // 1: proto.tlsparser.model.Certificate.notAfter:type_name -> google.protobuf.Timestamp
	3, // 2: proto.tlsparser.model.Certificate.lastScrape:type_name -> google.protobuf.Timestamp
	0, // 3: proto.tlsparser.model.TLSDetails.certificate:type_name -> proto.tlsparser.model.Certificate
	3, // 4: proto.tlsparser.model.TLSConnection.lastSeen:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_tlsparser_model_model_proto_init() }
func file_internal_proto_tlsparser_model_model_proto_init() {
	if File_internal_proto_tlsparser_model_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_tlsparser_model_model_proto_rawDesc), len(file_internal_proto_tlsparser_model_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_tlsparser_model_model_proto_goTypes,
		DependencyIndexes: file_internal_proto_tlsparser_model_model_proto_depIdxs,
		MessageInfos:      file_internal_proto_tlsparser_model_model_proto_msgTypes,
	}.Build()
	File_internal_proto_tlsparser_model_model_proto = out.File
	file_internal_proto_tlsparser_model_model_proto_goTypes = nil
	file_internal_proto_tlsparser_model_model_proto_depIdxs = nil
}
