---
apiVersion: v1
kind: Service
metadata:
  name: k8spacket
  labels:
    app.kubernetes.io/name: k8spacket
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: k8spacket
