name: reusable jobs

on:
  workflow_call:
    inputs:
      kernel:
        description: 'Kernel'
        required: true
        type: string

jobs:
  e2e-kernel:
    runs-on: ubuntu-24.04
    container:
      image: k8spacket/ci-e2e-test:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: k8spacket
      - name: Run e2e tests on kernel ${{ inputs.kernel }}
        run: |
          KERNEL=${{ inputs.kernel }} make e2e